service: sagemakerscheduler

provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sagemaker:DescribeTrainingJob
        - sagemaker:CreateTrainingJob
      Resource: "arn:aws:sagemaker:*:*:*"
    - Effect: "Allow"
      Action:
        - iam:PassRole
      # Don't forget to update the account number and the name of the SageMaker service role
      Resource: "arn:aws:iam::ACCOUNT_NUMBER:role/service-role/SAGEMAKER_SERVICE_ROLE"

stage: dev
region: us-east-1

functions:
  main:
    handler: handler.main
    events:
      - schedule: rate(5 minutes)
    environment:
      training_job_name: "DEMO-imageclassification-2018-05-10-09-58-12"
      training_job_prefix: "imageclassification"
      instance_type: "ml.p3.2xlarge"
      instance_count: "2"
